title: "Home"  # change to your name if you want that on the left
description: "Personal website and portfolio"
theme: minima
sass:
  style: compressed

url: "https://puriroshan.github.io"
baseurl: ""   # user site

header_pages:
  - projects.md
  - publications.md
  - cv.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  


