title: "Home"
description: "Personal website and portfolio"
theme: minima
sass:
  style: compressed

url: "https://puriroshan.github.io"
baseurl: ""   # keep empty for user site

# top navigation links
header_pages:
  - projects.md
  - publications.md
  - cv.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

