title: "Roshan Puri"                     # shows at top-left
description: "Postdoctoral Scholar · University of California, Davis"
theme: minima
markdown: kramdown

# Only show these pages in the top-right nav (NO index.md here)
header_pages:
  - publications.md
  - projects.md
  - cv.md
  - contact.md
